import { ResumeData } from "../types";

export const resumeData: ResumeData = {
    titleHeader: {
        name: "Mohit Uniyal",
        title: "Full Stack Developer",
        contact: {
            email: "m7uniyal@gmail.com",
            phone: "+91 7835816795",
            address: "Dehradun, India",
            _id: "38",
        },
        image: "https://avatars.githubusercontent.com/u/47273253?v=4",
        socials: [
            {
                name: "LinkedIn",
                url: "https://www.linkedin.com/in/mohit-uniyal-77183692/",
                _id: "35",
            },
            {
                name: "GitHub",
                url: "https://github.com/mohit-uniyal-dev",
                _id: "36",
            },
        ],
        _id: "34",
    },
    summary: {
        detailed:
            "Full Stack Developer with 8 years of experience, including 5 years in MEAN stack (MongoDB, Express.js, Angular, Node.js) and 3 years in MSBI (Microsoft Business Intelligence). Skilled in building scalable web applications, developing RESTful APIs, browser extensions, and integrating third-party APIs. Experienced in data visualization, automation, and performance optimization. Strong in problem-solving, team mentoring, and client communication. Currently expanding expertise in React.js while thriving in agile environments.",
        short: "MEAN STACK (5 Years) | MSBI (3 years)",
        _id: "33",
    },
    skills: {
        webTechnologies: [
            {
                name: "Angular",
                experience: "5 years",
                _id: "9",
                image: "",
                type: "web",
            },
            {
                name: "React",
                experience: "5 years",
                _id: "10",
                image: "",
                type: "web",
            },
            {
                name: "TypeScript",
                experience: "5 years",
                _id: "2",
                image: "",
                type: "web",
            },
            {
                name: "Node.js",
                experience: "5 years",
                _id: "11",
                image: "",
                type: "backend",
            },
            {
                name: "Express.js",
                experience: "5 years",
                _id: "12",
                image: "",
                type: "backend",
            },
            {
                name: "MongoDB",
                experience: "5 years",
                _id: "13",
                image: "",
                type: "database",
            },
            {
                name: "MySQL",
                experience: "2 years",
                _id: "14",
                image: "",
                type: "database",
            },
            {
                name: "Postman",
                experience: "5 years",
                _id: "18",
                image: "",
                type: "tool",
            },
            {
                name: "VS Code",
                experience: "8 years",
                _id: "19",
                image: "",
                type: "tool",
            },
            {
                name: "JIRA",
                experience: "8 years",
                _id: "19",
                image: "",
                type: "tool", 
            }
        ],
        browserExtension: [
            {
                name: "HTML",
                experience: "5 years",
                _id: "4",
                image: "",
                type: "web",
            },
            {
                name: "CSS",
                experience: "5 years",
                _id: "5",
                image: "",
                type: "web",
            },
            {
                name: "JavaScript",
                experience: "5 years",
                _id: "1",
                image: "",
                type: "web",
            },
            {
                name: "Bootstrap",
                experience: "5 years",
                _id: "7",
                image: "",
                type: "web",
            },
            {
                name: "jQuery",
                experience: "5 years",
                _id: "8",
                image: "",
                type: "web",
            },
        ],
        businessIntelligence: [
            {
                name: "SSIS",
                experience: "4 years",
                _id: "20",
                image: "",
                type: "ETL",
            },
            {
                name: "Power BI",
                experience: "1 years",
                _id: "22",
                image: "",
                type: "reporting",
            },
            {
                name: "Crystal Reports",
                experience: "1 years",
                _id: "23",
                image: "",
                type: "reporing",
            },
            {
                name: "Qlik View",
                experience: "1 years",
                _id: "24",
                image: "",
                type: "reporting",
            },
            {
                name: "Visual Studio",
                experience: "3 years",
                _id: "39",
                image: "",
                type: "IDE",
            },
            {
                name: "Github",
                experience: "8 years",
                _id: "16",
                image: "",
                type: "tool",
            },
            {
                name: "JIRA",
                experience: "7 years",
                _id: "17",
                image: "",
                type: "tool",
            },
            {
                name: "SQL Server",
                experience: "4 years",
                _id: "15",
                image: "",
                type: "database",
            },
        ],
    },
    projects: [
        {
            name: "Rezme Web Application",
            description:
                "Developed a web application that manages a white-label system for the Join Cherry Chrome extension, enabling seamless customization and integration for various clients",
            technologies: ["MEAN Stack"],
            url: "https://admin.rezme.com/login",
            _id: "25",
            type: "webTechnologies",
        },
        {
            name: "Join Cherry Web Application",
            description:
                "Built a web and Chrome extension-based platform that allows users to search for hotel and flight deals while displaying relevant browser extension data within a user-friendly dashboard",
            technologies: ["MEAN Stack"],
            url: "https://www.joincherry.com/",
            _id: "26",
            type: "webTechnologies",
        },
        {
            name: "Join Cherry Browser Extension",
            description:
                "Designed and developed a browser extension that integrates with various OTA platforms (e.g., Booking.com, Expedia) to provide users with exclusive discounts on hotels, attractions, and flights.",
            technologies: ["HTML", "CSS", "JavaScript"],
            url: "https://chromewebstore.google.com/detail/join-cherry-stop-overpayi/chdofjfbphhphdllcadpnaochgcapnid",
            _id: "27",
            type: "browserExtension",
        },
        {
            name: "Quick Snip",
            description:
                "A small browser extension to capture screenshot of web browser tabs, region or full page. Managing chrome store deployment, bug fixing etc",
            technologies: ["HTML", "CSS", "JQuery", "Bootstrap"],
            url: "https://chromewebstore.google.com/detail/Quick%20Snip/gjjhmphibjpmjbeghgjgecennojdohgc?hl=en&authuser=0",
            _id: "38",
            type: "browserExtension",
        },
        {
            name: "Synthesis",
            description:
                "Contributed to the development of a comprehensive order-to-cash management system tailored for the oil and gas industry, streamlining financial transactions and operational workflows.",
            technologies: ["T-SQL", "Crystal Reports"],
            url: "https://www.contata.com/oil-gas-software",
            _id: "28",
            type: "businessIntelligence",
        },
        {
            name: "HyperWallet: Financial/Loyalty Data Mart",
            description:
                "Contributed to the development of a comprehensive order-to-cash management system tailored for the oil and gas industry, streamlining financial transactions and operational workflows.",
            technologies: ["SSIS", "Power BI", "SQL Server"],
            url: "https://www.hyperwallet.com",
            _id: "29",
            type: "businessIntelligence",
        },

        {
            name: "My Web Resume",
            description:
                "The current resume site with admin panel to update resume",
            technologies: ["MERN Stack"],
            url: "",
            _id: "37",
            type: "webTechnologies",
        },
    ],
    workHistory: [
        {
            company: "Frooty Studios Pvt. Ltd",
            position: "Full Stack Developer",
            startDate: "2019-01-01",
            endDate: null,
            website: "https://www.frootystudios.com",
            reponsibilities: [
                "Developed a white-labeling system to automate Chrome extension customization for clients.",
                "Managed daily communication with UK-based clients for project coordination",
                "Led and mentored junior developers, ensuring best practices.",
                "Built Angular-based applications and RESTful APIs using Node.js & Express.js.",
                "Designed and optimized MongoDB/Mongoose databases for scalable solutions.",
                "Created API and project documentation using Postman.",
                "Used Git and branching strategies for seamless collaboration.",
                "Developed browser extensions for Chrome, Mozilla, and Edge using JavaScript, jQuery, and Bootstrap.",
                "Managed and automated extension store deployments via an integrated admin system.",
                "Researched and integrated third-party APIs (ZipTax, Beehiiv, Klaviyo, IATA Geo, AWS S3, SendGrid, Google APIs).",
            ],
            _id: "30",
        },
        {
            company: "Cyber Group Inc.",
            position: "BI Engineer",
            startDate: "2018-01-01",
            endDate: "2019-01-01",
            website: "https://www.cybergroup.in",
            reponsibilities: [
                "Developed and optimized QlikView reports for data visualization.",
                "Debugged and implemented MSBI ETL packages for efficient data processing",
                "Collaborated with clients to manage project tasks and deliverables.",
                "Mentored new trainees in MSBI technologies, ensuring smooth onboarding.",
            ],
            _id: "31",
        },
        {
            company: "Contata Solutions Pvt. Ltd",
            position: "Jr. System Analyst",
            startDate: "2016-01-01",
            endDate: "2018-01-01",
            website: "https://www.contata.com",
            reponsibilities: [
                "Developed and managed ETL packages for data processing",
                "Optimized T-SQL stored procedures for improved performance",
                "Designed Power BI reports for data visualization.",
                "Created and scheduled SQL Agent jobs for automated ETL execution.",
                "Translated client mockups into Crystal Reports using stored procedures.",
            ],
            _id: "32",
        },
    ],
};
