import { ResumeData } from "../types";

export const resumeData: ResumeData = {
    titleHeader: {
        name: "Mohit Uniyal",
        title: "Full Stack Developer",
        contact: {
            email: "m7uniyal@gmail.com",
            phone: "+91 7835816795",
            address: "Dehradun, India",
            _id: "1",
        },
        image: "https://avatars.githubusercontent.com/u/47273253?v=4",
        socials: [
            {
                name: "LinkedIn",
                url: "https://www.linkedin.com/in/mohit-uniyal-77183692/",
                _id: "2",
            },
            {
                name: "GitHub",
                url: "https://github.com/mohit-uniyal-dev",
                _id: "3",
            },
        ],
        _id: "4",
    },
    summary: {
        detailed:
            "Full-Stack Developer working in software delivery since 2016. I work across the modern TypeScript stack — Angular, React, and Node.js — and increasingly build AI-powered products with LLMs, alongside a background in browser extensions and Microsoft Business Intelligence.\n\nMy work spans scalable web applications, REST APIs, browser extensions, third-party and payment integrations, AI microservices, ETL workflows, and data visualizations. It also includes architecture, performance optimization, client communication, technical documentation, and mentoring developers in agile teams.",
        short: "Full-stack web · AI-powered products · Browser extensions",
        _id: "5",
    },
    skills: {
        webTechnologies: [
            {
                name: "Angular",
                experience: "5 years",
                _id: "6",
                image: "",
                type: "web",
            },
            {
                name: "React",
                experience: "Developing",
                _id: "7",
                image: "",
                type: "web",
            },
            {
                name: "OpenAI / LLMs",
                experience: "1 year",
                _id: "53",
                image: "",
                type: "ai",
            },
            {
                name: "TypeScript",
                experience: "5 years",
                _id: "8",
                image: "",
                type: "web",
            },
            {
                name: "Node.js",
                experience: "5 years",
                _id: "9",
                image: "",
                type: "backend",
            },
            {
                name: "Express.js",
                experience: "5 years",
                _id: "10",
                image: "",
                type: "backend",
            },
            {
                name: "MongoDB",
                experience: "5 years",
                _id: "11",
                image: "",
                type: "database",
            },
            {
                name: "MySQL",
                experience: "2 years",
                _id: "12",
                image: "",
                type: "database",
            },
            {
                name: "Postman",
                experience: "5 years",
                _id: "13",
                image: "",
                type: "tool",
            },
            {
                name: "VS Code",
                experience: "8 years",
                _id: "14",
                image: "",
                type: "tool",
            },
            {
                name: "JIRA",
                experience: "8 years",
                _id: "15",
                image: "",
                type: "tool",
            },
            {
                name: "Material UI",
                experience: "Developing",
                _id: "30",
                image: "",
                type: "web",
            },
        ],
        browserExtension: [
            {
                name: "HTML",
                experience: "5 years",
                _id: "16",
                image: "",
                type: "web",
            },
            {
                name: "CSS",
                experience: "5 years",
                _id: "17",
                image: "",
                type: "web",
            },
            {
                name: "JavaScript",
                experience: "5 years",
                _id: "18",
                image: "",
                type: "web",
            },
            {
                name: "Bootstrap",
                experience: "5 years",
                _id: "19",
                image: "",
                type: "web",
            },
            {
                name: "jQuery",
                experience: "5 years",
                _id: "20",
                image: "",
                type: "web",
            },
            {
                name: "VS Code",
                experience: "8 years",
                _id: "21",
                image: "",
                type: "tool",
            },
        ],
        businessIntelligence: [
            {
                name: "SSIS",
                experience: "4 years",
                _id: "22",
                image: "",
                type: "ETL",
            },
            {
                name: "T-SQL",
                experience: "4 years",
                _id: "23",
                image: "",
                type: "scripting",
            },
            {
                name: "Power BI",
                experience: "1 year",
                _id: "24",
                image: "",
                type: "reporting",
            },
            {
                name: "Crystal Reports",
                experience: "1 year",
                _id: "25",
                image: "",
                type: "reporting",
            },
            {
                name: "Qlik View",
                experience: "1 year",
                _id: "26",
                image: "",
                type: "reporting",
            },
            {
                name: "Visual Studio",
                experience: "3 years",
                _id: "27",
                image: "",
                type: "IDE",
            },
            {
                name: "GitHub",
                experience: "8 years",
                _id: "28",
                image: "",
                type: "tool",
            },
            {
                name: "JIRA",
                experience: "7 years",
                _id: "29",
                image: "",
                type: "tool",
            },
            {
                name: "SQL Server",
                experience: "4 years",
                _id: "46",
                image: "",
                type: "database",
            },
        ],
    },
    projects: [
        {
            name: "ClikJob — AI Job Application Platform",
            description:
                "Multi-tenant SaaS for AI-assisted job applications. Angular 19 admin & candidate portals backed by a Node/Express + MongoDB API with role-based access control, organization/candidate/invitation management, and full Stripe subscription billing — plan upgrades/downgrades with proration, immediate-vs-scheduled change routing, and monthly credit/parse metering with mid-cycle carry-forward. A dedicated OpenAI-powered microservice parses resumes and answers dynamic application questions, rate-limited via a job queue.",
            technologies: [
                "Angular 19",
                "TypeScript",
                "Node.js",
                "MongoDB",
                "Stripe",
                "OpenAI",
            ],
            url: "",
            _id: "51",
            type: "webTechnologies",
            ai: true,
            image: "/assets/clikjob-platform.png",
            techStack: "Angular · Node/Express · MongoDB · Stripe · OpenAI",
            responsibilities: [
                "Owned client communication, project management, and delivery.",
                "Led and mentored a team of two junior developers.",
                "Architected the multi-tenant solution and ran code reviews.",
                "Built the OpenAI-powered microservice for resume parsing and dynamic question answering.",
                "Implemented Stripe subscription billing with proration and credit metering.",
            ],
        },
        {
            name: "ClikJob — Job Application Autofill Extension",
            description:
                "A Manifest V3 Chrome extension that autofills job applications across 25+ ATS portals (Workday, Greenhouse, iCIMS, Oracle Cloud, SuccessFactors, Bullhorn, and more). It reads the candidate's saved profile, injects its UI through a shadow-DOM overlay, and calls the AI service to answer dynamic, non-mapped application questions — cutting apply time from minutes to seconds while tracking credit usage against the user's plan.",
            technologies: [
                "TypeScript",
                "Chrome Extension (MV3)",
                "Content Scripts",
                "Service Worker",
                "Shadow DOM",
            ],
            url: "",
            _id: "52",
            type: "browserExtension",
            ai: true,
            image: "/assets/clikjob-extension.png",
            techStack: "TypeScript · Chrome Extension (MV3) · REST APIs",
            responsibilities: [
                "Owned client communication, project management, and delivery.",
                "Led and mentored a team of two junior developers.",
                "Architected the autofill engine across 25+ ATS portals with a shadow-DOM overlay.",
                "Integrated the AI service to answer dynamic, non-mapped application questions.",
                "Ran code reviews and drove product delivery.",
            ],
        },
        {
            name: "Sanskrit Sansadhan",
            description:
                "Digital library and interactive Sanskrit learning portal for Uttarakhand Sanskrit Vishwavidyalaya — a manuscript viewer, searchable dictionary, and a canvas-based learning module for Hindi speakers.",
            technologies: ["React", "Pixi.js", "Node.js", "MongoDB"],
            url: "https://sanskritsansadhan.usv.ac.in",
            _id: "47",
            type: "webTechnologies",
            image: "/assets/sanskrit-sansadhan-web.png",
            techStack: "React + Pixi.js + Node/Express + MongoDB",
            responsibilities: [
                "Built an interactive Sanskrit learning canvas on Pixi.js v8 with five exercise types, rendered on WebGL with an accessible DOM mirror.",
                "Designed a shared-action layer so one tap drives both the canvas and its DOM mirror, keeping keyboard and screen-reader users at parity.",
                "Created an animated guru mascot with a four-mood state machine and eased animation blending.",
                "Added multilingual support (Hindi / English / Sanskrit) via i18next with in-lesson Hindi overrides.",
                "Wrote a Playwright canvas e2e suite (33 tests) and a Vitest bundle-budget guard (~46 KB gzip, 80 KB cap).",
                "Delivered accessibility: screen-reader mode, high-contrast, adjustable font size, and reduced-motion-aware animations.",
                "Built an admin CMS for chapters, lessons, exercises, dictionaries, courses, and PDF assets.",
            ],
        },
        {
            name: "SaMD Regulatory Assistant",
            description:
                "Pre-regulatory validation assistant for Software as a Medical Device. Guides teams through an EU MDR self-assessment using an AI clarification copilot plus a deterministic rules engine, then renders a classification dashboard and matching PDF report.",
            technologies: ["Angular", "Node.js", "MongoDB", "OpenAI"],
            url: "",
            _id: "48",
            type: "webTechnologies",
            ai: true,
            image: "/assets/samd-pre-regulatory-web.png",
            techStack: "Angular 18 + Tailwind + Node/Express + MongoDB + OpenAI",
            responsibilities: [
                "Built the regulatory navigation dashboard in Angular 18 (standalone components, signals, OnPush) with classification rationale, footnotes, next steps, and a similar-device carousel.",
                "Established a single-source content architecture so the on-screen dashboard and generated PDF can never drift.",
                "Rebuilt the server-side PDF generator with pdfkit, including a from-scratch table renderer for the assessment sections.",
                "Hardened the deterministic MDR Rule 11 / IEC 62304 engine with negation-aware feature interpretation and safety-class-driven wording.",
                "Designed a guardrail over the LLM copilot so it asks a clarifying question whenever the rules and outcome could disagree.",
                "Maintained ts-jest and Karma/Jasmine test suites and authored engineering docs.",
            ],
        },
        {
            name: "DealsDaddy — Coupon Extension",
            description:
                "Cross-browser extension that auto-detects supported merchants, fetches active coupons from a backend, and applies the best discount at checkout — with no user action needed.",
            technologies: ["TypeScript", "React", "Node.js", "MongoDB"],
            url: "",
            _id: "49",
            type: "browserExtension",
            image: "/assets/dealsdaddy-extension.png",
            techStack: "WXT (MV3) + TypeScript + React + Node/Express + MongoDB",
            responsibilities: [
                "Built a configurable apply engine that fills the coupon field, submits, and reads success/failure from the DOM via per-merchant selector configs, with best-coupon early exit.",
                "Added a two-layer cache in the MV3 service worker with configVersion-based invalidation so admin changes propagate without a TTL wait.",
                "Implemented platform auto-detection (Shopify, WooCommerce, BigCommerce) that drives fallback selector configs.",
                "Developed a Shadow-DOM-isolated floating widget with a MERCHANT_FOUND → APPLYING → SUCCESS / FAILED / MANUAL state machine.",
                "Used a MutationObserver reconciliation loop to keep widget state in sync with externally applied or removed coupons.",
                "Built an analytics pipeline that queues events and flushes them on an alarm, with once-per-session gating.",
            ],
        },
        {
            name: "DealsDaddy — Admin Console",
            description:
                "Full-stack admin platform for the DealsDaddy extension — a React dashboard for merchants, coupons, config templates, and users, backed by an Express API that also serves the extension's detection, config, coupon, and analytics endpoints.",
            technologies: ["React", "TypeScript", "Node.js", "MongoDB"],
            url: "",
            _id: "50",
            type: "webTechnologies",
            image: "/assets/dealsdaddy-admin.png",
            techStack: "React + TanStack Query + Node/Express + MongoDB",
            responsibilities: [
                "Built merchant and per-merchant config editors with a template system so one WooCommerce/Shopify template serves many merchants via overrides.",
                "Added coupon CRUD plus CSV/XLSX bulk upload with drag-and-drop, progress, and per-row error reporting.",
                "Developed a Recharts analytics dashboard with KPI cards, browser distribution, date ranges, and empty states.",
                "Engineered the config-resolution service merging shared templates with per-merchant overrides, with configVersion auto-bump via a Mongoose hook.",
                "Built the extension-facing API: merchant detection, versioned platform manifest, config resolution, coupon fetch, and analytics ingest.",
                "Implemented JWT extension auth (installId-scoped) and role-based admin auth.",
            ],
        },
        {
            name: "Rezme",
            description:
                "Developed a web application that manages a white-label system for the Join Cherry Chrome extension, enabling seamless customization and integration for various clients",
            technologies: ["Angular", "Node.js", "MongoDB"],
            url: "https://admin.rezme.com/login",
            _id: "31",
            type: "webTechnologies",
            image: "/assets/rezme.png",
            techStack: "Angular · Node/Express · MongoDB",
            responsibilities: [
                "Developed a white-labeling system to automate Chrome extension customization for clients.",
                "Managed daily communication with UK-based clients for project coordination",
                "Led and mentored junior developers, ensuring best practices.",
                "Built Angular-based applications and RESTful APIs using Node.js & Express.js.",
                "Designed and optimized MongoDB/Mongoose databases for scalable solutions.",
                "Created API and project documentation using Postman.",
                "Used Git and branching strategies for seamless collaboration.",
            ],
        },
        {
            name: "Join Cherry — Web Platform",
            description:
                "Built a web and Chrome extension platform that helps users find hotel and flight deals while presenting relevant extension data in a clear dashboard.",
            technologies: ["Angular", "Node.js", "MongoDB"],
            url: "https://www.joincherry.com/",
            _id: "32",
            type: "webTechnologies",
            image: "/assets/join-cherry-web.png",
            techStack: "Angular · Node/Express · MongoDB",
            responsibilities: [],
        },
        {
            name: "Join Cherry — Browser Extension",
            description:
                "Designed and developed a browser extension that integrates with various OTA platforms (e.g., Booking.com, Expedia) to provide users with exclusive discounts on hotels, attractions, and flights.",
            technologies: ["HTML", "CSS", "JavaScript"],
            url: "https://chromewebstore.google.com/detail/join-cherry-stop-overpayi/chdofjfbphhphdllcadpnaochgcapnid",
            _id: "33",
            type: "browserExtension",
            image: "/assets/join-cherry-extension.png",
            techStack: "Bootstrap & JS",
            responsibilities: [],
        },
        {
            name: "Minimine",
            description:
                "Built a web application and Chrome extension that help users save and manage job opportunities from LinkedIn.",
            technologies: ["Angular", "Node.js", "MongoDB"],
            url: "",
            _id: "34",
            type: "webTechnologies",
            image: "/assets/minimine.png",
            techStack: "Angular · Node/Express · MongoDB",
            responsibilities: [],
        },
        {
            name: "Quick Snip",
            description:
                "Maintained a browser extension for capturing visible tabs, selected regions, and full pages, including Chrome Web Store releases and bug fixes.",
            technologies: ["HTML", "CSS", "jQuery", "Bootstrap"],
            url: "https://chromewebstore.google.com/detail/Quick%20Snip/gjjhmphibjpmjbeghgjgecennojdohgc?hl=en&authuser=0",
            _id: "35",
            type: "browserExtension",
            image: "/assets/quick-snip.png",
            techStack: "Bootstrap & JS",
            responsibilities: [],
        },
        {
            name: "Al-go",
            description:
                "Built a browser extension that allows users to customize their YouTube feed.",
            technologies: ["HTML", "CSS", "jQuery", "Bootstrap"],
            url: "https://chromewebstore.google.com/detail/al-go/adjbkhalicehnbjboobhmhkakcgkmelb?hl=en",
            _id: "36",
            type: "browserExtension",
            image: "/assets/al-go.png",
            techStack: "Bootstrap & JS",
            responsibilities: [],
        },
        {
            name: "i-search",
            description:
                "allows Internet users to search the web in complete privacy and provides the essentials to take control of their personal information: tracker blocking, smarter encryption, and private search.",
            technologies: ["HTML", "CSS", "jQuery", "Bootstrap"],
            url: "https://addons.mozilla.org/en-US/firefox/addon/isearch/",
            _id: "37",
            type: "browserExtension",
            image: "/assets/i-search.png",
            techStack: "Bootstrap & JS",
            responsibilities: [],
        },
        {
            name: "Web Resume",
            description:
                "The current resume site with admin panel to update resume",
            technologies: ["React", "TypeScript", "Material UI"],
            url: "https://mohit7th.github.io/resume/",
            _id: "38",
            type: "webTechnologies",
            image: "/assets/web-resume.png",
            techStack: "React · TypeScript · Vite",
            responsibilities: [],
        },
        {
            name: "Financial Data Mart",
            description:
                "Implemented and deployed ETL packages for a financial and loyalty data mart.",
            technologies: ["SSIS", "Power BI", "SQL Server"],
            url: "https://www.hyperwallet.com",
            _id: "39",
            type: "businessIntelligence",
            image: "/assets/financial-data-mart.png",
            techStack: "MSBI",
            responsibilities: [],
        },
        {
            name: "Oil & Gas Reporting",
            description:
                "Contributed to the development business reports for the oil and gas industry, Implemented stored procedures for data reports.",
            technologies: ["T-SQL", "Crystal Reports"],
            url: "https://www.contata.com/oil-gas-software",
            _id: "40",
            type: "businessIntelligence",
            image: "/assets/oil-gas-reporting.png",
            techStack: "MSBI",
            responsibilities: [],
        },
        {
            name: "Real Estate Service",
            description:
                "Developed and maintained MSBI ETL packages, implemented QlikView reports, and coordinated project work with a US-based client.",
            technologies: ["SSIS", "T-SQL", "QlikView"],
            url: "https://cginfinity.com/data-analytics-ai",
            _id: "41",
            type: "businessIntelligence",
            image: "/assets/real-estate-service.png",
            techStack: "MSBI",
            responsibilities: [],
        },
        {
            name: "Patent Analytics",
            description:
                "Optimized slow-running queries and created stored procedures that consolidated repeated database operations.",
            technologies: ["MySQL"],
            url: "https://www.contata.com/case-studies/invent-management-system-for-an-ip-law-consulting-firm/",
            _id: "42",
            type: "businessIntelligence",
            image: "/assets/patent-analytics.png",
            techStack: "MySQL",
            responsibilities: [],
        },
    ],
    workHistory: [
        {
            company: "Frooty Studios Pvt. Ltd",
            position: "Full Stack Developer",
            startDate: "2019-07-01",
            endDate: null,
            website: "https://www.frootystudios.com",
            badge: "Co-founder",
            responsibilities: [
                "Developed a white-labeling system to automate Chrome extension customization for clients.",
                "Managed daily communication with UK-based clients for project coordination",
                "Led and mentored junior developers, ensuring best practices.",
                "Built Angular-based applications and RESTful APIs using Node.js & Express.js.",
                "Designed and optimized MongoDB/Mongoose databases for scalable solutions.",
                "Created API and project documentation using Postman.",
                "Used Git and branching strategies for seamless collaboration.",
                "Developed browser extensions for Chrome, Mozilla, and Edge using JavaScript, jQuery, and Bootstrap.",
                "Managed and automated extension store deployments via an integrated admin system.",
                "Researched and integrated third-party APIs (ZipTax, Beehiiv, Klaviyo, IATA Geo, AWS S3, SendGrid, Google APIs).",
            ],
            _id: "43",
            image: "/assets/website.svg",
        },
        {
            company: "Cyber Group Inc. / CG Infinity",
            position: "BI Engineer",
            startDate: "2018-08-01",
            endDate: "2019-08-01",
            website: "https://cginfinity.com",
            responsibilities: [
                "Developed and optimized QlikView reports for data visualization.",
                "Debugged and implemented MSBI ETL packages for efficient data processing",
                "Collaborated with clients to manage project tasks and deliverables.",
                "Mentored new trainees in MSBI technologies, ensuring smooth onboarding.",
            ],
            _id: "44",
            image: "/assets/data_visual.svg",
        },
        {
            company: "Contata Solutions Pvt. Ltd",
            position: "Jr. System Analyst",
            startDate: "2016-01-01",
            endDate: "2018-08-01",
            website: "https://www.contata.com",
            responsibilities: [
                "Developed and managed ETL packages for data processing",
                "Optimized T-SQL stored procedures for improved performance",
                "Designed Power BI reports for data visualization.",
                "Created and scheduled SQL Agent jobs for automated ETL execution.",
                "Translated client mockups into Crystal Reports using stored procedures.",
            ],
            _id: "45",
            image: "/assets/data.svg",
        },
    ],
    education: [
        {
            degree: "Master of Computer Applications (MCA)",
            institution: "Graphic Era University",
            startYear: "2014",
            endYear: "2016",
            _id: "60",
        },
        {
            degree: "Bachelor of Computer Applications (BCA)",
            institution: "Graphic Era University",
            startYear: "2011",
            endYear: "2014",
            _id: "61",
        },
    ],
};
